# Generated by Django 4.2.17 on 2025-01-06 09:51

import apps.accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=apps.accounts.fields.AvatarField(blank=True, null=True, upload_to=apps.accounts.fields._profile_avtar_filename),
        ),
    ]
