# Generated by Django 4.2.17 on 2025-01-06 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(blank=True, max_length=80, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(max_length=1023, verbose_name='Description')),
                ('term', models.CharField(default=None, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(blank=True, max_length=80, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(max_length=1023, verbose_name='Description')),
                ('term', models.CharField(default=None, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=80, verbose_name='Meta title')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta keywords')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('use_ssr', models.BooleanField(default=False, verbose_name='Use SSR')),
                ('render_url', models.CharField(blank=True, max_length=80, verbose_name='Render URL')),
                ('slug', models.CharField(blank=True, max_length=80, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField()),
                ('publication_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('post_type', models.CharField(max_length=20, verbose_name='Post Type')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.category')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
